config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/signup' =>'users#new'
  post '/signup' => 'users#create'
  
  delete '/logout' => 'sessions#destroy' #Don't use get for logout

  get '/auth/:provider/callback' => 'sessions#create'

  
  
  resources :demo_reports
  resources :bikes do
    resources :demo_reports, only: [:new, :index, :update] #nested route (shallow routing)
  end
  resources :dealers
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :demo_reports
    has_many :bikes, through: :demo_reports
    validates :email, uniqueness: true, presence: true
    validates :password, presence: true

    has_secure_password

    def self.omniauth_user(auth)
        self.find_or_create_by(email: auth[:info][:email]) do |user|#looks through db to see if email already exists (if not then initialize user)
            user.name = auth[:info][:name]
            user.password = SecureRandom.hex #generates a random hex string
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save #if true then log in user
            session[:user_id] = @user.id #adds the user to the session
            redirect_to user_path(@user)
        else #redirect to login page
            render :new
        end
    end

    def show
        #redirect_if_not_logged_in
        if current_user == User.find_by_id(params[:id])
            @user = User.find_by_id(params[:id]) #find_by_id allows redirect if there is no id
        else
            flash[:message] = "Click Home to go to your page"
            redirect_to '/'
        end
        #redirect_to '/' if !@user #redirects to index if there is no user
    end

    private

    def user_params #strong params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/new.html.erb
<h1>Sign Up For DemoDaze</h1>

<%= render partial: "/layouts/errors", locals: {object: @user} %>


<%= form_for @user do |f| %>
    <%=f.label :name %>
    <%=f.text_field :name %><br/>
    
    <%=f.label :email %>
    <%=f.email_field :email, required:true %><br/>
    
    <%=f.label :password %>
    <%=f.password_field :password, required:true %><br/>

    <%=f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%=@user.name%>!</h1>

<% if flash[:message] %>
    <%= flash[:message] %>
<% end %>

<h3>Your Demo Reports:</h3>
<% @user.demo_reports.each do |d| %>
    <p>Bike: <%=d.bike.name %></p>
    <p>Report: <%= d.report %></p>
    <%= button_to "Edit Report", edit_demo_report_path(d.id), method: :get %> 
    <%= button_to "Delete Report", demo_report_path(d.id), method: :delete %>
<% end %>