config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/signup' =>'users#new'
  post '/signup' => 'users#create'
  
  delete '/logout' => 'sessions#destroy' #Don't use get for logout

  get '/auth/:provider/callback' => 'sessions#create'

  
  
  resources :demo_reports
  resources :bikes do
    resources :demo_reports, only: [:new, :index, :update] #nested route (shallow routing)
  end
  resources :dealers
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :dealer
  has_many :demo_reports
  has_many :users, through: :demo_reports
  accepts_nested_attributes_for :dealer

  validates :name, presence: true
  validate :dealer_bike_uniquness


  def dealer_attributes=(attributes) #reader method for dealer nested form inside new bike form
    self.dealer = Dealer.find_or_create_by(attributes) if !attributes['name'].empty?
    self.dealer
  end

  def dealer_bike_uniquness
    #if a bike with that name already belongs to a dealer, don't create a new bike object
    if Bike.find_by(name: name, dealer_id: dealer_id) 
      errors.add(:name, "This bike already exists for this dealer. You can write a demo report for this bike on the bike page!")
    end
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        @bike = Bike.new
        @bike.build_dealer
    end
    
    def index
        @bikes = Bike.all
    end

    def show
        if  @bike = Bike.find_by_id(params[:id]) #if demo report exists
            @bike #display demo report page
       else
            flash[:message] = "That bike doesn't exist"
            redirect_to bikes_path #redirect to demo report index page
       end
    end

    def create
        @bike = Bike.new(bike_params)
        @bike.user_id = session[:user_id]
        if @bike.save
            redirect_to bike_path(@bike)
        else
            render :new
        end
    end

    private

    def bike_params #strong params
        params.require(:bike).permit(:name, :category, :dealer_id, dealer_attributes: [:name])
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/index.html.erb
<% if flash[:message] %>
    <%= flash[:message] %>
<% end %>

<h1>Bikes</h1>

<% @bikes.each do |bike| %>
    <h3><%= bike.name %></h3>
    <%= link_to "Create a Demo Report for this bike", new_bike_demo_report_path(bike.id)%><br>
    <%= link_to "View Bike", bike_path(bike.id) %>
<% end %>

app/views/bikes/new.html.erb
<h1>Add A Bike</h1>

<%= render partial: '/layouts/errors', locals: {object: @bike} %>

<%= form_for @bike do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>
    
  <%=f.label :category %>
  <%=f.text_field :category %>
    
  <h3>Select a Dealer: </h3>
  <div>
    <%= f.collection_select :dealer_id, Dealer.all, :id, :name, include_blank: 'Select Dealer'%>

  </div>

  <h4>Or create a new Dealer: </h4>
  <div>
    <%=f.fields_for :dealer do |b| %>
      <%= b.label :name %>
      <%= b.text_field :name %>
    <% end %>
  </div>
  <br>
  <div class="actions"><%= f.submit "Create Bike", :class => "submit" %></div>
<% end %>

app/views/bikes/show.html.erb
<h1><%= @bike.name %></h1> 
<p>Type: <%= @bike.category %><p>
 <%= link_to "View Reports", bike_demo_reports_path(@bike.id)%>