config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/signup' =>'users#new'
  post '/signup' => 'users#create'
  
  delete '/logout' => 'sessions#destroy' #Don't use get for logout

  get '/auth/:provider/callback' => 'sessions#create'

  
  
  resources :demo_reports
  resources :bikes do
    resources :demo_reports, only: [:new, :index, :update] #nested route (shallow routing)
  end
  resources :dealers
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this from being saved:
    </h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_logged_in.html.erb
<nav> 
    <%= link_to 'Home', user_path(current_user), class:'button' %>
    <%= link_to 'Add Bike', new_bike_path, class:'button'  %>
    <%= link_to 'Bikes', bikes_path, class:'button'  %>
    <%= link_to 'Demo Reports', demo_reports_path, class:'button'  %>
    <%= link_to 'Dealers', dealers_path, class:'button'  %>
    <%= link_to 'Logout', '/logout', method: :delete, class:'button'%>
</nav>

app/views/layouts/_logged_out.html.erb
<%= link_to "Login", login_path %>
<%= link_to "Signup", signup_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoDaze</title>
    <link rel="shortcut icon" href="http://www.example.com/myicon.ico"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class='navbar'><%= nav_bar %></nav>
  </head>
  <body>
    <div class="container text-center"">
      <%= yield %>
    </div>
  </body>
</html>